// Pure: render a MarketScore as a clean Markdown report for a paper appendix.

import type { MarketScore } from "../types";

export function toMarkdown(d: MarketScore): string {
  const lines: string[] = [];
  lines.push(`# Reliability report: ${d.market_question}`);
  lines.push("");
  lines.push(
    `**Verdict:** ${d.reliability_score}/100 (${d.band}). ${d.headline}`,
  );
  lines.push(`**Reliability snapshot as of:** ${d.as_of}`);
  lines.push("");
  lines.push("## Why");
  for (const r of d.reasons) {
    lines.push(`- **${r.headline}** (${r.severity}): ${r.detail}`);
  }
  lines.push("");
  lines.push("## Subscores");
  lines.push(`- Liquidity health: ${d.subscores.liquidity_health}/100`);
  lines.push(`- Trading-pattern integrity: ${d.subscores.anomaly}/100`);
  lines.push(`- Resolution quality: ${d.subscores.resolution_quality}/100`);
  lines.push("");
  lines.push("## Market facts");
  lines.push(`- Volume: $${d.meta.volume_usd.toLocaleString()}`);
  lines.push(`- Liquidity: $${d.meta.liquidity_usd.toLocaleString()}`);
  lines.push(`- Unique traders: ${d.meta.unique_traders.toLocaleString()}`);
  lines.push(`- Ends: ${d.meta.end_date}`);
  lines.push(`- Status: ${d.meta.resolved ? "Resolved" : "Open"}`);
  lines.push("");
  lines.push("## Citation (APA)");
  lines.push(`> ${d.citation.apa}`);
  lines.push("");
  lines.push(`Reproducible snapshot: ${d.permalink}`);
  lines.push("");
  lines.push(
    d.source === "mock"
      ? "_Generated by UW MarketLens (Mock mode — deterministic placeholder data)._"
      : "_Generated by UW MarketLens from live Polymarket data via the full S1–S7 pipeline._",
  );
  return lines.join("\n");
}
